### ISSUE TITLE
week4

### ISSUE THREAD

**Issue by divyanshisuri** [divyanshisuri/divya-suri-tri3#6]
## Grader: Riya/Kamryn 

Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented 
https://www.loom.com/share/e0b618ab65b04c99ae80b5d3d56cf17d 
- [x] Runtime of Code(with comments) on Replit/Intellij
- [x] Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [x] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [x] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack #2 Add logout to CRUD screen
- [x] Hack #3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by ranand2445** [comment]
Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x]  CB Create Task Coding requirements documented
- [x] https://www.loom.com/share/e0b618ab65b04c99ae80b5d3d56cf17d
- [x]  Runtime of Code(with comments) on Replit/Intellij
Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [ ]  Start or add to existing project: init.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project. Additionally, you should start with some of the content in templates and static folders. Find a pair and work on this together. Ask questions.
- [x]  Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes. It has some obvious flaws in its security. Discuss some of the flaws that you see in its security as implemented.
- [x]  Hack https://github.com/divyanshisuri/divya-suri-tri3/issues/1 Add Phone Number to Sign Up / Authorization screen
- [x]  Hack https://github.com/divyanshisuri/divya-suri-tri3/issues/2 Add logout to CRUD screen
- [x]  Hack https://github.com/divyanshisuri/divya-suri-tri3/issues/3 Add login_required to another portion of the project
- [ ]  Extra Credit: A quality design would have login and logout on Navbar with user information. Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Temporary Score: 3.5 - They let us know that they asked for an extension**
- Create Task: Video of runtime with comments and all requirements documented.
- Challenges: All code for the hacks is there but it's in one file and could use organization. Runtime isn't working on Intellij or Replit.
